// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         clientId: "clientId",
 *         clientSecret: "clientSecret",
 *         issuer: "issuer",
 *         authorizationEndpoint: "authorizationEndpoint",
 *         tokenEndpoint: "tokenEndpoint",
 *         userInfoEndpoint: "userInfoEndpoint"
 *     }
 */
export interface CreateSsoRequest {
    /** Provider name (e.g. Google) */
    name: string;
    clientId: string;
    clientSecret: string;
    issuer: string;
    authorizationEndpoint: string;
    tokenEndpoint: string;
    userInfoEndpoint: string;
}
