// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CreateSubscriberTagsRequest {
    /** Tag ID */
    id: string;
    /** Optional custom data */
    extendedData?: Record<string, unknown>;
}
