// This file was auto-generated by Fern from our API Definition.

export interface GetTagsResponse {
    data: GetTagsResponse.Data;
}

export namespace GetTagsResponse {
    export interface Data {
        items: Data.Items.Item[];
        /** Cursor for next page */
        nextCursor?: string;
        /** Total count of items */
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                /** Tag name */
                name: string;
                /** Tag slug (unique identifier) */
                slug?: string;
                /** Tag description */
                description?: string;
                /** Hex color code */
                color?: string;
                /** Extended data */
                extendedData?: Record<string, unknown>;
                id: string;
                /** Tag creation timestamp */
                createdAt: string;
                /** Tag last update timestamp */
                updatedAt: string;
            }
        }
    }
}
