// This file was auto-generated by Fern from our API Definition.

export interface GetTagSubscriberResponse {
    data: GetTagSubscriberResponse.Data;
}

export namespace GetTagSubscriberResponse {
    export interface Data {
        id: string;
        userId: string;
        tagId: string | null;
        user?: Data.User;
        createdAt: string;
    }

    export namespace Data {
        export interface User {
            id: string;
            username: string;
            displayName: string | null;
        }
    }
}
