// This file was auto-generated by Fern from our API Definition.

export interface UpdateTagsResponse {
    data?: UpdateTagsResponse.Data;
}

export namespace UpdateTagsResponse {
    export interface Data {
        /** Tag name */
        name: string;
        /** Tag slug (unique identifier) */
        slug?: string;
        /** Tag description */
        description?: string;
        /** Hex color code */
        color?: string;
        /** Extended data */
        extendedData?: Record<string, unknown>;
        id: string;
        /** Tag creation timestamp */
        createdAt: string;
        /** Tag last update timestamp */
        updatedAt: string;
    }
}
