// This file was auto-generated by Fern from our API Definition.

export const GetSearchRequestType = {
    Threads: "threads",
    Posts: "posts",
    Users: "users",
    Tags: "tags",
} as const;
export type GetSearchRequestType = (typeof GetSearchRequestType)[keyof typeof GetSearchRequestType];
