// This file was auto-generated by Fern from our API Definition.

import type * as Forum from "../../../index.js";

export interface ListTeamProvisioningResponse {
    data: ListTeamProvisioningResponse.Data;
}

export namespace ListTeamProvisioningResponse {
    export interface Data {
        handle: string;
        members: Forum.TeamMember[];
    }
}
