// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         handle: "handle",
 *         webhookId: "webhookId"
 *     }
 */
export interface DeleteWebhookProvisioningRequest {
    handle: string;
    webhookId: string;
}
