// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-provisioning-key": "x-provisioning-key",
 *         handle: "handle"
 *     }
 */
export interface GetOwnershipProvisioningRequest {
    /** Instance handle */
    handle: string;
    /** User provisioning key for platform-level instance management */
    "x-provisioning-key": string;
}
