// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         handle: "handle"
 *     }
 */
export interface ListDomainsProvisioningRequest {
    /** Instance handle */
    handle: string;
}
