// This file was auto-generated by Fern from our API Definition.

export interface GetWebhookDeliveryResponse {
    data: GetWebhookDeliveryResponse.Data;
}

export namespace GetWebhookDeliveryResponse {
    export interface Data {
        id: string;
        webhookId: string;
        event: string;
        payload: Record<string, unknown> | null;
        responseCode: number | null;
        responseBody: string | null;
        success: boolean;
        error: string | null;
        createdAt: string;
    }
}
