// This file was auto-generated by Fern from our API Definition.

export interface PollVotesResponse {
    data: PollVotesResponse.Data;
}

export namespace PollVotesResponse {
    export interface Data {
        id: string;
        pollId: string;
        optionId: string;
        userId: string;
        createdAt: string;
    }
}
