// This file was auto-generated by Fern from our API Definition.

export interface PostReaction {
    id: string;
    type: string;
    userId: string;
    user?: PostReaction.User;
    createdAt: string;
}

export namespace PostReaction {
    export interface User {
        id: string;
        username: string;
        displayName: string | null;
        bio: string | null;
        url: string | null;
        isOnline: boolean | null;
        roles?: User.Roles.Item[];
    }

    export namespace User {
        export type Roles = Roles.Item[];

        export namespace Roles {
            export interface Item {
                id: string;
                name: string;
                slug: string | null;
                color: string | null;
            }
        }
    }
}
