// This file was auto-generated by Fern from our API Definition.

export interface PrivateMessageReply {
    id: string;
    parentId: string | null;
    senderId: string;
    recipientId: string;
    body: string;
    status: string | null;
    createdAt: string;
}
