// This file was auto-generated by Fern from our API Definition.

export interface RoleList {
    /** Items per page (max 75) */
    limit?: number;
    /** Cursor for pagination */
    cursor?: string;
    /** Search by name or slug */
    search?: string;
    /** Sort order */
    sort?: RoleList.Sort;
}

export namespace RoleList {
    /** Sort order */
    export const Sort = {
        Newest: "newest",
        Oldest: "oldest",
        Name: "name",
    } as const;
    export type Sort = (typeof Sort)[keyof typeof Sort];
}
