// This file was auto-generated by Fern from our API Definition.

export interface ThreadPollListResponse {
    data: ThreadPollListResponse.Data;
}

export namespace ThreadPollListResponse {
    export interface Data {
        items: Data.Items.Item[];
        nextCursor?: string;
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                id: string;
                title: string;
                options: Item.Options.Item[];
                createdAt: string;
            }

            export namespace Item {
                export type Options = Options.Item[];

                export namespace Options {
                    export interface Item {
                        id: string;
                        title: string;
                        color: string | null;
                        _count?: Item.Count;
                    }

                    export namespace Item {
                        export interface Count {
                            votes: number;
                        }
                    }
                }
            }
        }
    }
}
