// This file was auto-generated by Fern from our API Definition.

export interface ThreadPostListResponse {
    data: ThreadPostListResponse.Data;
}

export namespace ThreadPostListResponse {
    export interface Data {
        items: Data.Items.Item[];
        nextCursor?: string;
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                id: string;
                threadId: string;
                userId: string;
                body: string;
                depth: number | null;
                user?: Item.User;
                _count?: Item.Count;
                createdAt: string;
                updatedAt: string;
            }

            export namespace Item {
                export interface User {
                    id: string;
                    username: string;
                    displayName: string | null;
                }

                export interface Count {
                    reactions: number;
                }
            }
        }
    }
}
