// This file was auto-generated by Fern from our API Definition.

import type * as Forum from "../index.js";

export interface Thread {
    /** Thread title */
    title: string;
    /** Thread content (Markdown supported) */
    body: string;
    /** Author user ID (required for API key auth, ignored for JWT auth) */
    userId?: string;
    /** List of tag slugs, names, or IDs to attach */
    tags?: string[];
    /** Poll data */
    poll?: Forum.ThreadPoll;
    id: string;
    /** URL-friendly identifier */
    slug: string | null;
    /** Whether thread is locked */
    locked: boolean | null;
    /** Whether thread is pinned */
    pinned: boolean | null;
    /** View count */
    views: number;
    /** Number of posts/replies */
    postsCount: number;
    /** Timestamp of the last post */
    lastPostAt: string | null;
    /** Custom metadata */
    extendedData: Record<string, unknown> | null;
    createdAt: string;
    updatedAt: string;
}
