// This file was auto-generated by Fern from our API Definition.

export interface ThreadPostResponse {
    data: ThreadPostResponse.Data;
}

export namespace ThreadPostResponse {
    export interface Data {
        id: string;
        threadId: string;
        userId: string;
        body: string;
        depth: number | null;
        user?: Data.User;
        _count?: Data.Count;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Data {
        export interface User {
            id: string;
            username: string;
            displayName: string | null;
        }

        export interface Count {
            reactions: number;
        }
    }
}
