// This file was auto-generated by Fern from our API Definition.

export interface ThreadPollListResponse {
    data: ThreadPollListResponse.Data;
}

export namespace ThreadPollListResponse {
    export interface Data {
        items: Data.Items.Item[];
        nextCursor?: string;
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                id: string;
                title: string;
                closed: boolean | null;
                closedAt: string | null;
                expiresAt: string | null;
                totalVotes: number;
                options: Item.Options.Item[];
                createdAt: string;
                updatedAt: string;
            }

            export namespace Item {
                export type Options = Options.Item[];

                export namespace Options {
                    export interface Item {
                        id: string;
                        title: string;
                        color: string | null;
                        votesCount: number;
                        extendedData: Record<string, unknown> | null;
                    }
                }
            }
        }
    }
}
