// This file was auto-generated by Fern from our API Definition.

export interface UserFollowerListResponse {
    data: UserFollowerListResponse.Data;
}

export namespace UserFollowerListResponse {
    export interface Data {
        items: Data.Items.Item[];
        nextCursor?: string;
        count: number;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                id: string;
                followerId: string;
                followingId: string;
                follower?: Item.Follower;
                createdAt: string;
            }

            export namespace Item {
                export interface Follower {
                    id: string;
                    username: string;
                    displayName: string | null;
                }
            }
        }
    }
}
