// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Forum from "../../../index.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations for webhooks
 */
export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve a paginated list of webhooks. Use cursor for pagination.
     *
     * **Requires feature: webhooks**
     *
     * @param {Forum.ListWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.list()
     */
    public list(
        request: Forum.ListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.WebhookListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Forum.ListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.WebhookListResponse>> {
        const { limit, cursor } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "webhooks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.WebhookListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/webhooks");
    }

    /**
     * Create a new webhook.
     *
     * **Requires feature: webhooks**
     *
     * @param {Forum.CreateWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.BadRequestError}
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.create({
     *         name: "name",
     *         url: "url",
     *         events: ["events"]
     *     })
     */
    public create(
        request: Forum.CreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.WebhookResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Forum.CreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.WebhookResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "webhooks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.WebhookResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Forum.BadRequestError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/webhooks");
    }

    /**
     * Retrieve a webhook by ID or slug (if supported).
     *
     * **Requires feature: webhooks**
     *
     * @param {Forum.RetrieveWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Forum.RetrieveWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.WebhookResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Forum.RetrieveWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.WebhookResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.WebhookResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/webhooks/{id}");
    }

    /**
     * Permanently delete a webhook.
     *
     * **Requires feature: webhooks**
     *
     * @param {Forum.DeleteWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Forum.DeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Forum.DeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SuccessResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/webhooks/{id}");
    }

    /**
     * Retrieve a paginated list of deliveries for Webhook.
     *
     * **Requires feature: webhooks**
     *
     * @param {Forum.ListDeliveriesWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.listDeliveries({
     *         id: "id"
     *     })
     */
    public listDeliveries(
        request: Forum.ListDeliveriesWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.WebhookDeliveryListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDeliveries(request, requestOptions));
    }

    private async __listDeliveries(
        request: Forum.ListDeliveriesWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.WebhookDeliveryListResponse>> {
        const { id, cursor, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `webhooks/${core.url.encodePathParam(id)}/deliveries`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.WebhookDeliveryListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/webhooks/{id}/deliveries");
    }

    /**
     * @param {Forum.RetrieveDeliveryWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.retrieveDelivery({
     *         id: "id",
     *         subId: "subId"
     *     })
     */
    public retrieveDelivery(
        request: Forum.RetrieveDeliveryWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.RetrieveDeliveryWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveDelivery(request, requestOptions));
    }

    private async __retrieveDelivery(
        request: Forum.RetrieveDeliveryWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.RetrieveDeliveryWebhooksResponse>> {
        const { id, subId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `webhooks/${core.url.encodePathParam(id)}/deliveries/${core.url.encodePathParam(subId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Forum.RetrieveDeliveryWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/webhooks/{id}/deliveries/{subId}",
        );
    }

    /**
     * @param {Forum.DeleteDeliveryWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.webhooks.deleteDelivery({
     *         id: "id",
     *         subId: "subId"
     *     })
     */
    public deleteDelivery(
        request: Forum.DeleteDeliveryWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDelivery(request, requestOptions));
    }

    private async __deleteDelivery(
        request: Forum.DeleteDeliveryWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SuccessResponse>> {
        const { id, subId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `webhooks/${core.url.encodePathParam(id)}/deliveries/${core.url.encodePathParam(subId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/webhooks/{id}/deliveries/{subId}",
        );
    }
}
