// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         title: "title",
 *         options: [{
 *                 title: "title"
 *             }]
 *     }
 */
export interface CreateThreadPollRequest {
    /** Thread ID */
    id: string;
    /** Poll question/title */
    title: string;
    /** Poll options (2-20) */
    options: CreateThreadPollRequest.Options.Item[];
    /** Optional expiration time */
    expiresAt?: string;
    /** Additional custom data */
    extendedData?: Record<string, unknown>;
}

export namespace CreateThreadPollRequest {
    export type Options = Options.Item[];

    export namespace Options {
        export interface Item {
            /** Option text */
            title: string;
            /** Optional color for display */
            color?: string;
            /** Additional custom data */
            extendedData?: Record<string, unknown>;
        }
    }
}
