// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title",
 *         body: "body"
 *     }
 */
export interface CreateThreadsRequest {
    /** Thread title */
    title: string;
    /** Thread content (Markdown supported) */
    body: string;
    /** Author user ID (required for API key auth, ignored for JWT auth) */
    userId?: string;
    /** List of tag slugs, names, or IDs to attach */
    tags?: string[];
    /** Poll data */
    poll?: CreateThreadsRequest.Poll;
    /** Lock thread on creation */
    locked?: boolean;
    /** Pin thread on creation */
    pinned?: boolean;
    /** Custom extended data */
    extendedData?: Record<string, unknown>;
}

export namespace CreateThreadsRequest {
    /**
     * Poll data
     */
    export interface Poll {
        /** Poll title */
        title: string;
        /** Poll options */
        options: Poll.Options.Item[];
    }

    export namespace Poll {
        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                title: string;
                color?: string;
                extendedData?: Record<string, unknown>;
            }
        }
    }
}
