// This file was auto-generated by Fern from our API Definition.

export interface GetAuthMeResponse {
    data: GetAuthMeResponse.Data;
}

export namespace GetAuthMeResponse {
    export interface Data {
        id: string;
        username: string;
    }
}
