// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RetrievePollRequest {
    /** Thread ID */
    id: string;
}
