// This file was auto-generated by Fern from our API Definition.

export interface DeleteThreadReactionResponse {
    data: DeleteThreadReactionResponse.Data;
}

export namespace DeleteThreadReactionResponse {
    export interface Data {
        success: boolean;
    }
}
