// This file was auto-generated by Fern from our API Definition.

export interface UpdateThreadResponse {
    data?: UpdateThreadResponse.Data;
}

export namespace UpdateThreadResponse {
    export interface Data {
        /** Thread title */
        title: string;
        /** Thread content (Markdown supported) */
        body: string;
        /** Author user ID (required for API key auth, ignored for JWT auth) */
        userId?: string;
        /** List of tag slugs, names, or IDs to attach */
        tags?: string[];
        /** Poll data */
        poll?: Data.Poll;
        id: string;
        /** URL-friendly identifier */
        slug: string | null;
        /** Whether thread is locked */
        locked: boolean | null;
        /** Whether thread is pinned */
        pinned: boolean | null;
        /** View count */
        views: number;
        /** Number of posts/replies */
        postsCount: number;
        /** Timestamp of the last post */
        lastPostAt: string | null;
        /** Custom metadata */
        extendedData: Record<string, unknown> | null;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Data {
        /**
         * Poll data
         */
        export interface Poll {
            /** Poll title */
            title: string;
            /** Poll options */
            options: Poll.Options.Item[];
        }

        export namespace Poll {
            export type Options = Options.Item[];

            export namespace Options {
                export interface Item {
                    title: string;
                    color?: string;
                    extendedData?: Record<string, unknown>;
                }
            }
        }
    }
}
