// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Forum from "../../../index.js";

export declare namespace SsOsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations for sso
 */
export class SsOsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SsOsClient.Options>;

    constructor(options: SsOsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     *
     * **Requires feature: sso**
     *
     * @param {Forum.ListSsOsRequest} request
     * @param {SsOsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.ssOs.listSsOs()
     */
    public listSsOs(
        request: Forum.ListSsOsRequest = {},
        requestOptions?: SsOsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SsoListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSsOs(request, requestOptions));
    }

    private async __listSsOs(
        request: Forum.ListSsOsRequest = {},
        requestOptions?: SsOsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SsoListResponse>> {
        const { cursor, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (cursor != null) {
            _queryParams.cursor = cursor;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "sso",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SsoListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/sso");
    }

    /**
     * Create an new sso.
     *
     * **Requires feature: sso**
     *
     * @param {Forum.CreateSsoRequest} request
     * @param {SsOsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.BadRequestError}
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.ssOs.createSso({
     *         name: "name",
     *         clientId: "clientId",
     *         clientSecret: "clientSecret",
     *         issuer: "issuer",
     *         authorizationEndpoint: "authorizationEndpoint",
     *         tokenEndpoint: "tokenEndpoint",
     *         userInfoEndpoint: "userInfoEndpoint"
     *     })
     */
    public createSso(
        request: Forum.CreateSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SsoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSso(request, requestOptions));
    }

    private async __createSso(
        request: Forum.CreateSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SsoResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                "sso",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SsoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Forum.BadRequestError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/sso");
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     *
     * **Requires feature: sso**
     *
     * @param {Forum.GetSsoRequest} request
     * @param {SsOsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.ssOs.getSso({
     *         id: "id"
     *     })
     */
    public getSso(
        request: Forum.GetSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SsoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSso(request, requestOptions));
    }

    private async __getSso(
        request: Forum.GetSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SsoResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `sso/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SsoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/sso/{id}");
    }

    /**
     * Permanently delete an sso.
     *
     * **Requires feature: sso**
     *
     * @param {Forum.DeleteSsoRequest} request
     * @param {SsOsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.ssOs.deleteSso({
     *         id: "id"
     *     })
     */
    public deleteSso(
        request: Forum.DeleteSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSso(request, requestOptions));
    }

    private async __deleteSso(
        request: Forum.DeleteSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.SuccessResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `sso/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/sso/{id}");
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     *
     * **Requires feature: sso**
     *
     * @param {Forum.UpdateSsoRequest} request
     * @param {SsOsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Forum.BadRequestError}
     * @throws {@link Forum.UnauthorizedError}
     * @throws {@link Forum.PaymentRequiredError}
     * @throws {@link Forum.NotFoundError}
     * @throws {@link Forum.TooManyRequestsError}
     * @throws {@link Forum.InternalServerError}
     *
     * @example
     *     await client.ssOs.updateSso({
     *         id: "id"
     *     })
     */
    public updateSso(
        request: Forum.UpdateSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): core.HttpResponsePromise<Forum.UpdateSsoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateSso(request, requestOptions));
    }

    private async __updateSso(
        request: Forum.UpdateSsoRequest,
        requestOptions?: SsOsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Forum.UpdateSsoResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ForumEnvironment.Production,
                `sso/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Forum.UpdateSsoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Forum.BadRequestError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 401:
                    throw new Forum.UnauthorizedError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Forum.PaymentRequiredError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Forum.NotFoundError(_response.error.body as Forum.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Forum.TooManyRequestsError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Forum.InternalServerError(
                        _response.error.body as Forum.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ForumError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/sso/{id}");
    }
}
