// This file was auto-generated by Fern from our API Definition.

export interface DeletePostReactionResponse {
    data: DeletePostReactionResponse.Data;
}

export namespace DeletePostReactionResponse {
    export interface Data {
        success: boolean;
    }
}
