// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("RolesClient", () => {
    test("listRoles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ name: "name", id: "id", createdAt: "createdAt", updatedAt: "updatedAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/roles").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.roles.listRoles();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        name: "name",
                        id: "id",
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listRoles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.listRoles();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listRoles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.listRoles();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listRoles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.listRoles();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listRoles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.listRoles();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createRole (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.roles.createRole({
            name: "name",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("createRole (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.createRole({
                name: "x",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createRole (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.createRole({
                name: "x",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createRole (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.createRole({
                name: "x",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createRole (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.createRole({
                name: "x",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createRole (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/roles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.createRole({
                name: "x",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getRole (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.roles.getRole({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("getRole (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.getRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getRole (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.getRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getRole (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.getRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getRole (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.getRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getRole (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/roles/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.getRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteRole (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.roles.deleteRole({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteRole (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.deleteRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteRole (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.deleteRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteRole (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.deleteRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteRole (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.deleteRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteRole (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/roles/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.roles.deleteRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updateRole (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.roles.updateRole({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("updateRole (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updateRole (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updateRole (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("updateRole (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updateRole (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updateRole (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/roles/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.roles.updateRole({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
