// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SsOsClient", () => {
    test("listAllSsOs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [
                    {
                        id: "id",
                        provider: "OKTA",
                        domain: "domain",
                        active: true,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/sso").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.listAllSsOs();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        provider: "OKTA",
                        domain: "domain",
                        active: true,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listAllSsOs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listAllSsOs();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listAllSsOs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listAllSsOs();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listAllSsOs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listAllSsOs();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listAllSsOs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listAllSsOs();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createAnSso (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            clientId: "clientId",
            clientSecret: "clientSecret",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ssOs.createAnSso({
            name: "name",
            clientId: "clientId",
            clientSecret: "clientSecret",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("createAnSso (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createAnSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createAnSso (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createAnSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createAnSso (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createAnSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createAnSso (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createAnSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createAnSso (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createAnSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getAnSso (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.getAnSso({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("getAnSso (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getAnSso (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getAnSso (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getAnSso (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getAnSso (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteAnSso (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.deleteAnSso({
            id: "id",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("deleteAnSso (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteAnSso (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteAnSso (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteAnSso (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteAnSso (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updateAnSso (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ssOs.updateAnSso({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("updateAnSso (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updateAnSso (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updateAnSso (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("updateAnSso (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updateAnSso (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updateAnSso (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateAnSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
