// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SsOsClient", () => {
    test("listSSOs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [
                    {
                        id: "id",
                        provider: "OKTA",
                        domain: "domain",
                        active: true,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/sso").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.listSsOs();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        provider: "OKTA",
                        domain: "domain",
                        active: true,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listSSOs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listSsOs();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listSSOs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listSsOs();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listSSOs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listSsOs();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listSSOs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.listSsOs();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createSSO (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            clientId: "clientId",
            clientSecret: "clientSecret",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ssOs.createSso({
            name: "name",
            clientId: "clientId",
            clientSecret: "clientSecret",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("createSSO (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createSSO (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createSSO (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createSSO (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createSSO (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            clientId: "x",
            clientSecret: "x",
            issuer: "issuer",
            authorizationEndpoint: "authorizationEndpoint",
            tokenEndpoint: "tokenEndpoint",
            userInfoEndpoint: "userInfoEndpoint",
        };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/sso")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.createSso({
                name: "x",
                clientId: "x",
                clientSecret: "x",
                issuer: "issuer",
                authorizationEndpoint: "authorizationEndpoint",
                tokenEndpoint: "tokenEndpoint",
                userInfoEndpoint: "userInfoEndpoint",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getSSO (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.getSso({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("getSSO (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getSSO (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getSSO (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getSSO (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getSSO (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/sso/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.getSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteSSO (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ssOs.deleteSso({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteSSO (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteSSO (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteSSO (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteSSO (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteSSO (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/sso/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ssOs.deleteSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updateSSO (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ssOs.updateSso({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                provider: "OKTA",
                domain: "domain",
                active: true,
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("updateSSO (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updateSSO (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updateSSO (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("updateSSO (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updateSSO (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updateSSO (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/sso/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ssOs.updateSso({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
