// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TagsClient", () => {
    test("listTags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ name: "name", id: "id", createdAt: "createdAt", updatedAt: "updatedAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/tags").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tags.listTags();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        name: "name",
                        id: "id",
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listTags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.listTags();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listTags (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.listTags();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("listTags (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.listTags();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listTags (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.listTags();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createTag (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tags.createTag({
            name: "name",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("createTag (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.createTag({
                name: "x",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createTag (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.createTag({
                name: "x",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createTag (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.createTag({
                name: "x",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("createTag (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.createTag({
                name: "x",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createTag (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.createTag({
                name: "x",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getTag (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tags.getTag({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("getTag (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.getTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getTag (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.getTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("getTag (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.getTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getTag (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.getTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getTag (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/tags/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.getTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteTag (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tags.deleteTag({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteTag (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.deleteTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteTag (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.deleteTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("deleteTag (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.deleteTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteTag (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.deleteTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteTag (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/tags/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tags.deleteTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updateTag (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: { key: "value" },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tags.updateTag({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                name: "name",
                slug: "slug",
                description: "description",
                color: "color",
                extendedData: {
                    key: "value",
                },
                id: "id",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("updateTag (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updateTag (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updateTag (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("updateTag (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updateTag (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updateTag (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/tags/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.updateTag({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listTagSubscribers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ id: "id", userId: "userId", tagId: null, createdAt: "createdAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tags.listTagSubscribers({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        userId: "userId",
                        tagId: null,
                        createdAt: "createdAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listTagSubscribers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.listTagSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listTagSubscribers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.listTagSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listTagSubscribers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.listTagSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listTagSubscribers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.listTagSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("getTagSubscriber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                userId: "userId",
                tagId: "tagId",
                user: { id: "id", username: "username", displayName: "displayName" },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tags.getTagSubscriber({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                userId: "userId",
                tagId: "tagId",
                user: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("getTagSubscriber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.getTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("getTagSubscriber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.getTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("getTagSubscriber (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.getTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("getTagSubscriber (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.getTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteTagSubscriber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tags.deleteTagSubscriber({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteTagSubscriber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.deleteTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteTagSubscriber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.deleteTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteTagSubscriber (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.deleteTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteTagSubscriber (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/tags/id/subscribers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tags.deleteTagSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
