// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ThreadsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [
                    {
                        title: "title",
                        body: "body",
                        id: "id",
                        slug: null,
                        locked: null,
                        pinned: null,
                        views: 1,
                        postsCount: 1,
                        lastPostAt: null,
                        extendedData: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/threads").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.list();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        title: "title",
                        body: "body",
                        id: "id",
                        slug: null,
                        locked: null,
                        pinned: null,
                        views: 1,
                        postsCount: 1,
                        lastPostAt: null,
                        extendedData: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.list();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.list();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.list();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.list();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", body: "body" };
        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.create({
            title: "title",
            body: "body",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.create({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.create({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.create({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.create({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", body: "x" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.create({
                title: "x",
                body: "x",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.retrieve({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.delete({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/threads/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: { title: "title", options: [{ title: "title" }] },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.update({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                title: "title",
                body: "body",
                userId: "userId",
                tags: ["tags"],
                poll: {
                    title: "title",
                    options: [
                        {
                            title: "title",
                        },
                    ],
                },
                id: "id",
                slug: "slug",
                locked: true,
                pinned: true,
                views: 1,
                postsCount: 1,
                lastPostAt: "lastPostAt",
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listPosts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [
                    {
                        id: "id",
                        threadId: "threadId",
                        userId: "userId",
                        body: "body",
                        depth: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/threads/id/posts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.listPosts({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        threadId: "threadId",
                        userId: "userId",
                        body: "body",
                        depth: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listPosts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/posts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listPosts({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listPosts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/posts").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listPosts({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listPosts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/posts").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listPosts({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listPosts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/posts").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.listPosts({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrievePost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                threadId: "threadId",
                userId: "userId",
                body: "body",
                depth: 1,
                user: { id: "id", username: "username", displayName: "displayName" },
                _count: { reactions: 1.1 },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .get("/threads/id/posts/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.retrievePost({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                threadId: "threadId",
                userId: "userId",
                body: "body",
                depth: 1,
                user: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                },
                _count: {
                    reactions: 1.1,
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("retrievePost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/posts/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrievePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrievePost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/posts/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrievePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrievePost (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/posts/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrievePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrievePost (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/posts/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrievePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deletePost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/threads/id/posts/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.deletePost({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deletePost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/posts/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deletePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deletePost (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/posts/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deletePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deletePost (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/posts/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deletePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deletePost (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/posts/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deletePost({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listReactions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ id: "id", type: "type", userId: "userId", createdAt: "createdAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server
            .mockEndpoint()
            .get("/threads/id/reactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.listReactions({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        type: "type",
                        userId: "userId",
                        createdAt: "createdAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listReactions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listReactions({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listReactions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listReactions({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listReactions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listReactions({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listReactions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listReactions({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createReaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = {
            data: {
                id: "id",
                type: "type",
                userId: "userId",
                user: { id: "id", username: "username", displayName: "displayName" },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.createReaction({
            id: "id",
            type: "LIKE",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                type: "type",
                userId: "userId",
                user: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("createReaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createReaction({
                id: "id",
                type: "LIKE",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createReaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createReaction({
                id: "id",
                type: "LIKE",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createReaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createReaction({
                id: "id",
                type: "LIKE",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("createReaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createReaction({
                id: "id",
                type: "LIKE",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createReaction (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "LIKE" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createReaction({
                id: "id",
                type: "LIKE",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteReaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.deleteReaction({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteReaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteReaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteReaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteReaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieveReaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                type: "type",
                userId: "userId",
                user: { id: "id", username: "username", displayName: "displayName" },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .get("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.retrieveReaction({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                type: "type",
                userId: "userId",
                user: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("retrieveReaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieveReaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieveReaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieveReaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/reactions/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveReaction({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listSubscribers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ id: "id", userId: "userId", threadId: null, createdAt: "createdAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.listSubscribers({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        userId: "userId",
                        threadId: null,
                        createdAt: "createdAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listSubscribers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listSubscribers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listSubscribers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listSubscribers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listSubscribers({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieveSubscriber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                userId: "userId",
                threadId: "threadId",
                user: { id: "id", username: "username", displayName: "displayName" },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.retrieveSubscriber({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                userId: "userId",
                threadId: "threadId",
                user: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("retrieveSubscriber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieveSubscriber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieveSubscriber (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieveSubscriber (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.retrieveSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteSubscriber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.deleteSubscriber({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteSubscriber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteSubscriber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteSubscriber (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteSubscriber (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/threads/id/subscribers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.deleteSubscriber({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrievePoll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                title: "title",
                options: [{ id: "id", title: "title", color: null }],
                createdAt: "createdAt",
            },
        };
        server.mockEndpoint().get("/threads/id/poll").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.threads.retrievePoll({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                title: "title",
                options: [
                    {
                        id: "id",
                        title: "title",
                        color: null,
                    },
                ],
                createdAt: "createdAt",
            },
        });
    });

    test("retrievePoll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/poll").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrievePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrievePoll (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/poll").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrievePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrievePoll (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/poll").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrievePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrievePoll (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/threads/id/poll").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.threads.retrievePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createPoll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", options: [{ title: "title" }] };
        const rawResponseBody = {
            data: {
                id: "id",
                title: "title",
                options: [{ id: "id", title: "title", color: null }],
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.createPoll({
            id: "id",
            title: "title",
            options: [
                {
                    title: "title",
                },
            ],
        });
        expect(response).toEqual({
            data: {
                id: "id",
                title: "title",
                options: [
                    {
                        id: "id",
                        title: "title",
                        color: null,
                    },
                ],
                createdAt: "createdAt",
            },
        });
    });

    test("createPoll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", options: [{ title: "x" }, { title: "x" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createPoll({
                id: "id",
                title: "x",
                options: [
                    {
                        title: "x",
                    },
                    {
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createPoll (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", options: [{ title: "x" }, { title: "x" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createPoll({
                id: "id",
                title: "x",
                options: [
                    {
                        title: "x",
                    },
                    {
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createPoll (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", options: [{ title: "x" }, { title: "x" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createPoll({
                id: "id",
                title: "x",
                options: [
                    {
                        title: "x",
                    },
                    {
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("createPoll (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", options: [{ title: "x" }, { title: "x" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createPoll({
                id: "id",
                title: "x",
                options: [
                    {
                        title: "x",
                    },
                    {
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createPoll (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "x", options: [{ title: "x" }, { title: "x" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.createPoll({
                id: "id",
                title: "x",
                options: [
                    {
                        title: "x",
                    },
                    {
                        title: "x",
                    },
                ],
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("updatePoll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                title: "title",
                options: [{ id: "id", title: "title", color: null }],
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.updatePoll({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                title: "title",
                options: [
                    {
                        id: "id",
                        title: "title",
                        color: null,
                    },
                ],
                createdAt: "createdAt",
            },
        });
    });

    test("updatePoll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updatePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("updatePoll (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updatePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("updatePoll (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updatePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("updatePoll (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updatePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("updatePoll (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/threads/id/poll")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.updatePoll({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
