// This file was auto-generated by Fern from our API Definition.

import * as Forum from "../../src/api/index";
import { ForumClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [
                    {
                        id: "id",
                        username: "username",
                        email: null,
                        displayName: null,
                        bio: null,
                        signature: null,
                        url: null,
                        isOnline: null,
                        lastSeenAt: null,
                        extendedData: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server.mockEndpoint().get("/users").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.list();
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        username: "username",
                        email: null,
                        displayName: null,
                        bio: null,
                        signature: null,
                        url: null,
                        isOnline: null,
                        lastSeenAt: null,
                        extendedData: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.list();
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.list();
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.list();
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.list();
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "username" };
        const rawResponseBody = {
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [{ id: "id", name: "name", slug: null, color: null }],
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.create({
            username: "username",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [
                    {
                        id: "id",
                        name: "name",
                        slug: null,
                        color: null,
                    },
                ],
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "foo" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.create({
                username: "foo",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "foo" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.create({
                username: "foo",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "foo" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.create({
                username: "foo",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "foo" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.create({
                username: "foo",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { username: "foo" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.create({
                username: "foo",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [{ id: "id", name: "name", slug: null, color: null }],
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.retrieve({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [
                    {
                        id: "id",
                        name: "name",
                        slug: null,
                        color: null,
                    },
                ],
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().get("/users/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.delete({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server.mockEndpoint().delete("/users/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.delete({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [{ id: "id", name: "name", slug: null, color: null }],
                extendedData: { key: "value" },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.update({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                username: "username",
                email: "email",
                displayName: "displayName",
                bio: "bio",
                signature: "signature",
                url: "url",
                postsCount: 1,
                threadsCount: 1,
                isOnline: true,
                lastSeenAt: "lastSeenAt",
                roles: [
                    {
                        id: "id",
                        name: "name",
                        slug: null,
                        color: null,
                    },
                ],
                extendedData: {
                    key: "value",
                },
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.PaymentRequiredError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/users/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.update({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listFollowers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ id: "id", followerId: "followerId", followingId: "followingId", createdAt: "createdAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server
            .mockEndpoint()
            .get("/users/id/followers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.listFollowers({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        followerId: "followerId",
                        followingId: "followingId",
                        createdAt: "createdAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listFollowers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowers({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listFollowers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowers({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listFollowers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowers({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listFollowers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowers({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("createFollower (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                follower: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [{ id: "id", name: "name", slug: null, color: null }],
                    extendedData: { key: "value" },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.createFollower({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                follower: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [
                        {
                            id: "id",
                            name: "name",
                            slug: null,
                            color: null,
                        },
                    ],
                    extendedData: {
                        key: "value",
                    },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("createFollower (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.createFollower({
                id: "id",
            });
        }).rejects.toThrow(Forum.BadRequestError);
    });

    test("createFollower (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.createFollower({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("createFollower (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.createFollower({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("createFollower (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.createFollower({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("createFollower (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/users/id/followers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.createFollower({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieveFollower (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                follower: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [{ id: "id", name: "name", slug: null, color: null }],
                    extendedData: { key: "value" },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .get("/users/id/followers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.retrieveFollower({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                follower: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [
                        {
                            id: "id",
                            name: "name",
                            slug: null,
                            color: null,
                        },
                    ],
                    extendedData: {
                        key: "value",
                    },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("retrieveFollower (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieveFollower (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieveFollower (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieveFollower (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/followers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteFollower (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/users/id/followers/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.deleteFollower({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteFollower (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/followers/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteFollower (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/followers/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteFollower (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/followers/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteFollower (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/followers/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollower({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("listFollowing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                items: [{ id: "id", followerId: "followerId", followingId: "followingId", createdAt: "createdAt" }],
                nextCursor: "nextCursor",
                count: 1,
            },
        };
        server
            .mockEndpoint()
            .get("/users/id/following")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.listFollowing({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                items: [
                    {
                        id: "id",
                        followerId: "followerId",
                        followingId: "followingId",
                        createdAt: "createdAt",
                    },
                ],
                nextCursor: "nextCursor",
                count: 1,
            },
        });
    });

    test("listFollowing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowing({
                id: "id",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("listFollowing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowing({
                id: "id",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("listFollowing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowing({
                id: "id",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("listFollowing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.listFollowing({
                id: "id",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("retrieveFollowing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                following: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [{ id: "id", name: "name", slug: null, color: null }],
                    extendedData: { key: "value" },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        };
        server
            .mockEndpoint()
            .get("/users/id/following/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.retrieveFollowing({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                followerId: "followerId",
                followingId: "followingId",
                following: {
                    id: "id",
                    username: "username",
                    displayName: "displayName",
                    bio: "bio",
                    signature: "signature",
                    url: "url",
                    postsCount: 1,
                    threadsCount: 1,
                    isOnline: true,
                    lastSeenAt: "lastSeenAt",
                    roles: [
                        {
                            id: "id",
                            name: "name",
                            slug: null,
                            color: null,
                        },
                    ],
                    extendedData: {
                        key: "value",
                    },
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
                createdAt: "createdAt",
            },
        });
    });

    test("retrieveFollowing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("retrieveFollowing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("retrieveFollowing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("retrieveFollowing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/users/id/following/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.retrieveFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });

    test("deleteFollowing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { success: true } };
        server
            .mockEndpoint()
            .delete("/users/id/following/subId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.deleteFollowing({
            id: "id",
            subId: "subId",
        });
        expect(response).toEqual({
            data: {
                success: true,
            },
        });
    });

    test("deleteFollowing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/following/subId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.UnauthorizedError);
    });

    test("deleteFollowing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/following/subId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.NotFoundError);
    });

    test("deleteFollowing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/following/subId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.TooManyRequestsError);
    });

    test("deleteFollowing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ForumClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/users/id/following/subId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.deleteFollowing({
                id: "id",
                subId: "subId",
            });
        }).rejects.toThrow(Forum.InternalServerError);
    });
});
