// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         subId: "subId"
 *     }
 */
export interface DeleteFollowerByIdUsersRequest {
    /** User ID */
    id: string;
    /** Follower ID */
    subId: string;
}
