// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetUsersRequest {
    /** Items per page (max 75) */
    limit?: number;
    /** Pagination cursor */
    cursor?: string;
    search?: string;
}
